### ISSUE TITLE
Update link to Piper download

### ISSUE THREAD

**Issue by aaronsdevera** [OpenInterpreter/01#100] opened 2024-03-22 01:00 UTC
**Describe the bug**
When running `01` locally, `piper` fails to download due to a bad url.

**To Reproduce**
1. on macOS, run `poetry run 01 --local` in the `/software` dir without `piper` model downloaded
2. See error

**Expected behavior**
`01` is supposed to go and download `piper` via the defined URL:

```
PIPER_URL = "https://github.com/rhasspy/piper/releases/latest/download/"
```

However I am not aware if GitHub supports these types of URLs any longer. For instance, https://github.com/rhasspy/piper/releases/latest/ will redirect you to the page on GitHub for the latest release. Adding `download` to that URL will redirect to a GitHub 404.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 - python3.11

**Comment by quentinsteinke** [comment] 2024-03-23 00:30
@aaronsdevera if you have the entire file name, not just to the latest folder, it will actually download it. I have tried it and got it working on my macOS using python3.11. The error is because of a ssl certificate validation problem. I am not sure what is wrong though. If I make it so the https request doesn't have to be verified (which you shouldn't do) in the tts.py, it works as intended.

**Comment by tyfiero** [comment] 2024-03-28 21:56
I believe this has been fixed with the latest merged pull requests. If the issue arises again, please create a new issue!

**Closed by tyfiero** 2024-03-28 21:56 UTC
